### ISSUE TITLE
Search bar to search for files in a given directory.

### ISSUE THREAD

**Issue by danielsleo** [Jack-Meade/BlackSphere#21]
A user should be able to search for a file in any given directory preferably using Ajax to to show files that match the string typed. 
Example: User types in 'd' which displays automatically all files beginning with 'd'.. 
                 User types in 'do' which displays all files beginning with 'do'
Where files name such as document.pdf would be displayed.

**Comment by Jack-Meade** [comment]
Search bar implemented
