### ISSUE TITLE
Stop back button from leaving site

### ISSUE THREAD

**Issue by Jack-Meade** [Jack-Meade/BlackSphere#22]
Back button will leave site if user comes immediate from other site.

# To Replicate
1. Login to BlackSphere
2. Go to another site
3. Go back to BlackSphere
4. Press back button

**Comment by AhernEYeldarB** [comment]
Why don't you try to change the back button implementation to return the "./.." dir as opposed to using the browser back function

**Comment by Jack-Meade** [comment]
Back button now goes up one dir.
